apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: eksclusters.k8s.shred.cloud
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: k8s.shred.cloud/v1alpha1
    kind: ekscluster
  resources: