apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: ekscluster
  annotations:
    provider: aws
spec:
  crossplane:
    version: ">=v1.10.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: ">=v0.19.0"
