apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: tenant
spec:
  crossplane:
    version: ">=v1.10.0-0"
  dependsOn:
    - provider: crossplane/provider-kubernetes
      version: ">=v0.5.0"
