apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nginx-ingress
spec:
  template:
    spec:
      containers:
      - name: nginx-nginx-ingress
        ports:
        - name: http
          hostPort: 80
        - name: https
          hostPort: 443

