apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: managedprojects.k8s.shred.cloud
spec:
  group: k8s.shred.cloud
  names:
    kind: xmanagedproject
    plural: xmanagedprojects
  claimNames:
    kind: managedproject
    plural: managedprojects
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  poc:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      organization:
                        type: string
                  initialize: 
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        templateName:
                          type: string 
                  environments:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                        path:
                          type: string 
                  build:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                        path:
                          type: string 
                  deploy:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                        path:
                          type: string 
                        other:
                          type: string
                  compliance:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                        path:
                          type: string 
          status:
            type: object
            properties:
              namespace:
                description: Random Namespace created for this project
                type: string
                    