apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  credentials:
    source: Filesystem
    fs:
      path: /vault/secrets/creds.txt
---