kind:
  ingress:
    enabled: false

preload:
  gitRepos:
  helmCharts:
  Containers:
  

gitea:
  gitea:
    config:
      server:
        ROOT_URL: "http://mgmt-gitea-http:3000"
      webhook:
        ALLOWED_HOST_LIST: "*"
  memcached:
    enabled: false
  persistence:
    enabled: false
  postgresql:
    persistence:
      enabled: false
  # ingress:
  #   enabled: true
  #   hosts:
  #     - paths:
  #       - path: "/git"
  #         pathType: Prefix
harbor:
  externalURL: "https://harbor.default.svc.cluster.local"
  persistence:
    enabled: false
  trivy:
    enabled: false
  notary:
    enabled: false
  expose:
    type: clusterIP
    tls:
      auto:
        commonName: harbor.default.svc.cluster.local
    # tls:
    #   enabled: false
argo-cd:
  dex:
    enabled: false
  # redis:
  #   enabled: false
  notifications:
    enabled: false
  repositories:
    istio-helm-repo:
      url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
      name: istio.io
      type: helm

argo-workflows:
  server:
    extraArgs:
      - --auth-mode=server

argo-events: {}


# nginx-ingress:
#   controller:
#     service:
#       type: NodePort
#       # httpPort:
#       #   nodePort: 80
#       # httpsPort:
#       #   nodePort: 443