apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: gkecluster
  annotations:
    provider: gcp
spec:
  crossplane:
    version: ">=v1.10.0-0"
  dependsOn:
    - provider: crossplane/provider-gcp
      version: ">=v0.22.0"
