apiVersion: k8s.shred.cloud/v1alpha1
kind: project
metadata:
  name: "myproject"
  namespace: "default"
spec:
  parameters:
    poc: 
      name: Matthew Ruge
      email: matthew.ruge@shrgroupllc.com
      organization: SHR
    initialize:
      - type: git
        templateName: shrProject
    # environments:
    #   - name: Dev
    #     template: aws-environment
    # build:
    #   - name: myApplication
    #     type: argo-workflow
    #     path: ./src/
    # deploy:
    #   - name: Integration
    #     path: ./chart/
    #     other: |-
    #       version: latest
    # compliance:
    #   - name: MyApplicationComponent
    #     type: OSCAL
    #     path: ./compliance/myapp-cdef.xml



