apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-vault-config
annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  args:
    - --debug
  metadata:
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "crossplane-providers"
      vault.hashicorp.com/agent-inject-secret-creds.txt: "secret/provider-creds/aws-default"
      vault.hashicorp.com/agent-inject-template-creds.txt: |
        {{ "{{" }}- with secret "secret/provider-creds/aws-default" -{{ "}}" }}
          [default]
          aws_access_key_id="{{ "{{" }} .Data.data.access_key {{ "}}" }}"
          aws_secret_access_key="{{ "{{" }} .Data.data.secret_key {{ "}}" }}"
        {{ "{{" }}- end -{{ "}}" }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.33.0
  controllerConfigRef:
    name: aws-vault-config
---
