apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
spec:
  project: management
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.20.8
    helm:
      parameters:
        - name: server.extraArgs[0]
          value: "--auth-mode=server"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: management
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: events
spec:
  project: management
  source:
    chart: argo-events
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.0.6
  destination:
    server: "https://kubernetes.default.svc"
    namespace: management
  syncPolicy:
    automated:
      selfHeal: true
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo
# spec:
#   project: management
#   source:
#     chart: argo-cd
#     repoURL: https://argoproj.github.io/argo-helm
#     targetRevision: 5.13.8
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: management
#   syncPolicy:
#     automated:
#       selfHeal: true
