apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  project: management
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.10.0
    helm:
      parameters:
        - name: args.0
          value: "--enable-external-secret-stores"
        - name: customAnnotations.vault.hashicorp.com/agent-inject
          value: "true"
        - name: customAnnotations.vault.hashicorp.com/agent-inject-token
          value: "true"
        - name: customAnnotations.vault.hashicorp.com/role
          value: "crossplane"
        - name: customAnnotations.vault.hashicorp.com/agent-run-as-user
          value: "65532"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: management
  syncPolicy:
    automated:
      selfHeal: true

---