apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: akscluster
  annotations:
    provider: azure
spec:
  crossplane:
    version: ">=v1.10.0-0"
  dependsOn:
    - provider: crossplane/provider-azure
      version: v0.19.0
