apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-admin
rules:
- apiGroups: ["*"] 
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: management
roleRef:
  kind: ClusterRole 
  name: crd-admin
  apiGroup: rbac.authorization.k8s.io